AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 100

Naming/VariableName:
  Enabled: true

Naming/PredicateName:
  Enabled: true

Naming/MethodParameterName:
  Enabled: false
